const cacheName = "app-cache-v1";
const filesToCache = [
    "./",
    "./index.html",
    "./css/style.css",
    "./js/script.js",
    "./manifest.json",
    "./icon-512x512.PNG",
    "./images/about.png",
    "./images/home.png",
    "./images/icon-512x512.PNG",
    "./images/icons8-c-sharp-logo-50.png",
    "./images/lastproject1.jpg",
    "./images/lastproject10.jpg",
    "./images/lastproject11.jpg",
    "./images/lastproject12.jpg",
    "./images/lastproject2.jpg",
    "./images/lastproject3.jpg",
    "./images/lastproject4.jpg",
    "./images/lastproject5.jpg",
    "./images/lastproject6.jpg",
    "./images/lastproject7.jpg",
    "./images/lastproject8.jpg",
    "./images/lastproject9.jpg"
];
